<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alexis Cohen, Andrianne Dao, Isabel Gomez, Jenny Smetzer, and Albert Y. Kim">
<meta name="dcterms.date" content="2022-12-07">

<title>Predictive Factors of Math SAT Score in Massachusetts Public and Charter High Schools</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="Term_paper_files/libs/clipboard/clipboard.min.js"></script>
<script src="Term_paper_files/libs/quarto-html/quarto.js"></script>
<script src="Term_paper_files/libs/quarto-html/popper.min.js"></script>
<script src="Term_paper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Term_paper_files/libs/quarto-html/anchor.min.js"></script>
<link href="Term_paper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Term_paper_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Term_paper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Term_paper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Term_paper_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predictive Factors of Math SAT Score in Massachusetts Public and Charter High Schools</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Alexis Cohen, Andrianne Dao, Isabel Gomez, Jenny Smetzer, and Albert Y. Kim </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 7, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">

</div>
<div class="cell">

</div>
<hr>
<p><img src="https://i2.wp.com/www.markstivers.com/cartoons/Stivers%2011-9-02%20SAT%20waiter.gif?zoom=2_" class="img-fluid" width="400"></p>
<section id="introduction" class="level1">
<h1>1. Introduction</h1>
<p>Many schools in the US are failing<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. This study aims to better understand how school conditions influence student performance. The SATs are an important part of many high school senior’s college application, and represent one measure of student performance. Our project investigates whether factors such as the percentage of economically disadvantaged students in a school and school size are related to student performance, as measured by a schools’ average SAT score.</p>
<p>To address this question, we used a data set from Kaggle that compiled information on public and charter schools in the state of Massachusetts from several Massachusetts Department of Education reports<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. The data was last updated in August of 2017. Each case in the data set is a school. Although this data set includes schools with grades K-8, we only focused on high school with 11th and 12th grades, as these are the grades in which students typically take SAT scores.</p>
<p>Unfortunately, the data does not contain overall SAT scores, only averaged Math and Verbal and Writing SAT scores for each school. After doing an exploratory data analysis, we saw that these three sub-types demonstrated similar trends. Therefore, we decided to focus solely on the Math SAT score (out of 800 points) as our outcome variable in order to make this report more concise. We included two explanatory variables in this analysis: the percent of students in a school that are considered economically disadvantaged, and school size, with three levels, “small” (&lt; 342 students), “medium” (342-541 students), and “large” (&gt; 541 students).</p>
<p>Here is a snapshot of 5 randomly chosen rows of the data set we’ll use:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  school_name                                  average_sat_math percen…¹ schoo…²
  &lt;chr&gt;                                                   &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt;  
1 Joseph Case High                                          539     21.6 medium 
2 Nauset Regional High                                      530     17.9 large  
3 A North Central Charter Essential (District)              507     31.1 medium 
4 Pathfinder Vocational Technical                           432     36.6 large  
5 Boston Community Leadership Academy                       431     56   medium 
# … with abbreviated variable names ¹​percent_economically_disadvantaged,
#   ²​school_size</code></pre>
</div>
</div>
<hr>
</section>
<section id="exploratory-data-analysis" class="level1">
<h1>2. Exploratory data analysis</h1>
<p>We had an original sample size of 390 high schools. However since 58 of these had missing SAT scores, we dropped these from consideration. Unfortuanately, no information was provided as to why some schools had missing values and most didn’t, so we cannot comment on the impact dropping these missing cases has on our results.</p>
<p>Our total sample size was 332 (Table 1). The mean of the average SAT scores was greatest for large schools (n = 238, <span class="math inline">\(\bar{x}\)</span> = 517.5, sd = 56.2), intermediate for medium schools (n = 74, <span class="math inline">\(\bar{x}\)</span> = 483.3, sd = 58.7), and lowest for small schools (n = 78, <span class="math inline">\(\bar{x}\)</span> = 478.0, sd = 77.4). In MA in 2017, the average percentage of economically disadvantaged students in schools was 31 % (sd = 21.74),</p>
<p>The percentage of students that were considered economically disadvantaged ranged from 3.1% to a shockingly high 93.9% (<span class="math inline">\(\bar{x}\)</span> = 31.6, sd = 21.7).</p>
<hr>
<p>Table 1. Summary statistics of average Math SAT scores for small, medium and large high schools in the State of Massachusetts in 2017.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  school_size     n  mean median    sd   min   max
  &lt;fct&gt;       &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 small          28  478.    476  77.4   364   741
2 medium         69  483.    502  58.7   347   601
3 large         235  518.    521  56.2   336   658</code></pre>
</div>
</div>
<hr>
<p>Looking at the distribution of Average Math SAT score in Figure 1, it does not appear to be skewed and thus we did not apply any transformations. We did notice a potential outlier around a score of 750, which is something to consider throughout our analysis.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Term_paper_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="614"></p>
<p></p><figcaption class="figure-caption">Figure 1. Distribution of average Math SAT scores in the State of Massachusetts in 2017</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In Figure 2, we generated a scatterplot to see the overall relationship between our numerical outcome variable Math SAT score and our numerical explanatory variable percentage of economically disadvantaged students. As the percentage of economically disadvantaged students increased, there was an associated decrease in Math SAT score. Consistent with this relationship is this is negative correlation coefficient of -0.83.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Term_paper_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="614"></p>
<p></p><figcaption class="figure-caption">Figure 2. Scatterplot of relationship between Math SAT score and percentage of study body that is economically disadvantaged in MA Schools in 2017.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Looking at Figure 3, which displays the relationship between our numerical outcome variable Math SAT score and our categorical explanatory variable school size, the Math SAT scores look to be the greatest at larger schools, and the lowest at smaller schools, though the difference does not seem to be extreme. Furthemore, there appear to be some potential outliers. In particular, there is one small school with a very high average SAT score. Small schools also have the largest variation in Math SAT scores as evidenced by the largest interquartile range.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Term_paper_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="614"></p>
<p></p><figcaption class="figure-caption">Figure 3. Boxplot of relationship between Math SAT score and school size category in MA Schools in 2017</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Finally, we generated a colored scatterplot displaying the relationship between all three variables at once in Figure 4. While this plot corresponds to an interaction model where we allow for each regression line corresponding to each school size to have a different slope, we observe that the slopes appear to be fairly similar, and thus the regression lines are roughly parallel. The additional complexity of the interaction model model thus appears to not be warranted, and thus we will favor the simpler “parallel slopes” model in our regression analysis.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Term_paper_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="614"></p>
<p></p><figcaption class="figure-caption">Figure 4. Colored scatterplot of relationship between Math SAT score and both percentage of study body that is economically disadvantaged and school size in MA Schools in 2017.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="multiple-linear-regression" class="level1">
<h1>3. Multiple linear regression</h1>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">3.1 Methods</h2>
<p>The components of our multiple linear regression model are the following:</p>
<ul>
<li>Outcome variable <span class="math inline">\(y\)</span> = Average Math SAT score</li>
<li>Numerical explanatory variable <span class="math inline">\(x_1\)</span> = Percentage of students who are economically disadvantaged</li>
<li>Categorical explanatory variable <span class="math inline">\(x_2\)</span> = School size</li>
</ul>
<p>where the unit of analysis is high school, given that each row in our dataset corresponds to a unique high school. As discussed earlier, we did not include an interaction effect because the slopes appear to be reasonably parallel in Figure 4.</p>
</section>
<section id="model-results" class="level2">
<h2 class="anchored" data-anchor-id="model-results">3.2 Model Results</h2>
<hr>
<p>Table 2. Regresstion table of parallel slopes model of average Math SAT as a function of percentage of economically disadvantaged student and school size.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
  term                           estim…¹ std_e…² stati…³ p_value lower…⁴ upper…⁵
  &lt;chr&gt;                            &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 intercept                       588.     7.61   77.3     0      573.    603.  
2 percent_economically_disadvan…   -2.78   0.106 -26.1     0       -2.99   -2.57
3 school_size: medium             -11.9    7.54   -1.58    0.115  -26.7     2.91
4 school_size: large               -6.36   6.92   -0.919   0.359  -20.0     7.26
# … with abbreviated variable names ¹​estimate, ²​std_error, ³​statistic,
#   ⁴​lower_ci, ⁵​upper_ci</code></pre>
</div>
</div>
<hr>
</section>
<section id="interpreting-the-regression-table" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-the-regression-table">3.3 Interpreting the regression table</h2>
<p>The regression equation for Math SAT score is the following:</p>
<p><span class="math display">\[
\begin{aligned}\widehat {score} =&amp; b_{0} + b_{prct} \cdot prct + b_{med} \cdot 1_{is\ med}(x_2) + b_{large} \cdot 1_{is\ large}(x_2) \\
=&amp; 588.190 - 2.777 \cdot prct - 11.913 \cdot 1_{is\ med}(x_2) - 6.362 \cdot 1_{is\ large}(x_2)
\end{aligned}
\]</span></p>
<ul>
<li>The intercept (<span class="math inline">\(b_0\)</span> = 588.190) represents the Math SAT score when zero percent of the students are said to be economically disadvantaged and the school size is small (Table 2).</li>
<li>The estimate for the slope for percent economically disadvantaged (<span class="math inline">\(b_{prct}\)</span> = -2.777) is the associated change in average Math SAT score depending on the percentage of economically disadvantaged students. Based on this estimate, for every one percentage point increase in the percent of economically disadvantaged students in a school, there was an associted decrease in Math SAT scores of on average 2.777 points.</li>
<li>The estimate for sizeMedium (<span class="math inline">\(b_{med}\)</span> = -11.913) and sizeLarge (<span class="math inline">\(b_{large}\)</span> = -6.36) are the offsets in intercept relative to the baseline group’s, sizeSmall, intercept (Table 2). In other words, on average medium schools score 11.913 points lower than small schools while large schools scored on average 6.362 lower.</li>
</ul>
<p>Thus the three regression lines have equations:</p>
<p><span class="math display">\[
\begin{aligned}
\text{Small schools (in red)}: \widehat {score} =&amp; 588.190 - 2.777 \cdot prct\\
\text{Medium schools (in green)}: \widehat {score} =&amp; 576.277 - 2.777 \cdot prct\\
\text{Large schools (in blue)}: \widehat {score} =&amp; 581.828 - 2.777 \cdot prct
\end{aligned}
\]</span></p>
</section>
<section id="inference-for-multiple-regression" class="level2">
<h2 class="anchored" data-anchor-id="inference-for-multiple-regression">3.4 Inference for multiple regression</h2>
<p>Using the output of our regression table we’ll test two different null hypotheses. The first null hypothesis is that there is no relationship between the percentage of economically disadvantaged students and Math SAT score at the population level (the population slope is zero).</p>
<p><span class="math display">\[\begin{aligned} H_0:&amp;\beta_{prct} = 0 \\\ \mbox{vs }H_A:&amp; \beta_{prct} \neq 0 \end{aligned}\]</span></p>
<p>There appears to be a negative relationship between the percent of economically disadvantaged students and mean SAT score for schools <span class="math inline">\(b_{prct}\)</span> = -2.77. Furthermore, this appears to be a meaningful relationship since in Table 2 we see</p>
<ul>
<li>the 95% confidence interval for the population slope <span class="math inline">\(\beta_{prct}\)</span> is (-2.986, -2.568), entirely on the negative side</li>
<li>the p-value <span class="math inline">\(p &lt; 0.001\)</span> is rather small, so we reject the null hypothesis <span class="math inline">\(H_0\)</span> that <span class="math inline">\(\beta_{prct} = 0\)</span> in favor of the alternative <span class="math inline">\(H_A\)</span> that <span class="math inline">\(\beta_{prct}\)</span> is indeed not 0 and negative.</li>
</ul>
<p>So taking into account potential sampling variation in results (for example if we collected similar data but for a different year or for a different nearby state for example) the relationship does appear to be negative.</p>
<p>The second set of null hypotheses that we are test are that all the differences in intercept for the non-baseline groups (medium and large schools) are zero.</p>
<p><span class="math display">\[
\begin{aligned}
H_0:&amp; \beta_{med} = 0\\
\mbox{vs }H_A:&amp; \beta_{med} \neq 0
\end{aligned}
\]</span> and <span class="math display">\[
\begin{aligned}
H_0:&amp; \beta_{large} = 0\\
\mbox{vs }H_A:&amp; \beta_{large} \neq 0
\end{aligned}
\]</span></p>
<p>In other words “is the intercept for the small schools equal to the intercepts for the medium schools or not?” As well as “is the intercept for the small schools equal to the intercepts for the large schools or not?” While both observed differences in intercept were negative (<span class="math inline">\(b_{med}\)</span> = -11.913 and <span class="math inline">\(b_{large}\)</span> = -6.362) we observe in Table 2 that</p>
<ul>
<li>the 95% confidence intervals for the population difference in intercept <span class="math inline">\(\beta_{med}\)</span> and <span class="math inline">\(\beta_{large}\)</span> both include 0: (-26.736, 2.909) and (-19.981, 7.258) respectively. So it is plausible that the difference of both intercepts are zero, hence it is plausible that all intercepts are the same.</li>
<li>The respective p-values are fairly large (0.115 and 0.359), so we fail to reject both null hypothesis that they are 0.</li>
</ul>
<p>So it appears the differences in intercept are not meaninfully different from 0, and hence all three intercepts are roughly equal. This consistent with our observations from the visualization of the three regression lines in Figure 4.</p>
</section>
<section id="residual-analysis" class="level2">
<h2 class="anchored" data-anchor-id="residual-analysis">3.5 Residual Analysis</h2>
<p>We conducted a residual analysis to see if there was any systematic pattern of residuals for the statistical model we ran. Because if there are systematic patterns, then we cannot fully trust our confidence intervals and p-values above.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Term_paper_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="614"></p>
<p></p><figcaption class="figure-caption">Figure 5. Histogram of residuals for statistical model</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Term_paper_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="614"></p>
<p></p><figcaption class="figure-caption">Figure 6. Scatterplots of residuals against the numeric explanatory variable.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Term_paper_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="614"></p>
<p></p><figcaption class="figure-caption">Figure 7. Scatterplots of residuals against the fitted values.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Term_paper_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="614"></p>
<p></p><figcaption class="figure-caption">Figure 8. Boxplot of residuals for each school size.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The model residuals were normally distributed, though there was one potential outlier (Fig. 5). There are not any systematic patterns to either of the scatterplots (Fig 6 &amp; 7). There is, however, one clear outlier around 5% in Figure 6 and at a very high mean SAT score in Figure 7. The boxplots show a very even spread of residuals at each school size, and similar values across the different school sizes. However, there is again, one particularly extreme outlier in the small school group (Fig. 8). We conclude that the assumptions for inference in multiple linear regression are well met. However, it might be worthwhile to look at whether the outlier with the very high scoring small school (MA Academy for Math and Science School) had a very large influence on the conclusions.</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>4. Discussion</h1>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">4.1 Conclusions</h2>
<p>We found that there was no significant difference in Math SAT scores at different sized schools, but that as the percentage of economically disadvantaged students increased, the scores decreased significantly. On average, Math SAT scores decreased by on average 3 points for every one unit increase in the percentage of economically disadvantaged students. This however does not necessarily mean that economic disadvantage <em>causes</em> lower test scores, merely that they are associated. We were surprised to find that school size did not have a significant influence on SAT scores. We expected to see higher SAT scores in small schools, assuming that students could get more one-on-one attention from teachers.</p>
<p>Overall, these results suggest that the economic well being of families is a factor in academic success. Our findings are consistent with previous studies showing that found wealth is correlated to SAT scores in the US<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. In order to mitigate this, we believe that there should be more support systems in schools with higher percentages of economically disadvantaged students. These could include free SAT prep courses or college readiness programs. Furthermore, programs that help remove barriers to education (transportation, hunger, etc.) may benefit overall student learning, and outcomes. The trends found in this analysis are important because SAT scores are a factor for college acceptances, which in our current society is a often a prerequisite for higher paying jobs.</p>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">4.2 Limitations</h2>
<p>There were several limitations to this data set. For one, 58 out of the 390 high schools were missing SAT score data. A close inspection revealed that these were mostly small schools in which less than five students took the SAT. Furthermore, these data only for the state of Massachusetts in 2017. As such, our scope of inference is limited to Massachusetts; it may not be appropriate to generalize the results found to the country as a whole. Massachusetts has been ranked #1 for public school systems by multiple sources including Forbes, and this may affect the trends seen in the data relative to other states<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. Additionally, a low score on the Math subsection is not necessarily indicative of a low total SAT score. However, since total SAT scores were not included in this data set, this was not a measure we could look at. Finally, standardized test results and graduation rates were the only measures of student success in this data set. We chose SAT scores as our outcome variable for this study due to this limitation. However, we recognize that standardized testing is not likely the best indicator of student success and intelligence. Not every school requires their students to take the SAT and these tests are expensive, which can act as a barrier for some students.</p>
</section>
<section id="further-questions" class="level2">
<h2 class="anchored" data-anchor-id="further-questions">4.3 Further questions</h2>
<p>If we were to continue researching this topic, we would like to work with a data set that includes total SAT score instead of just the sub-type scores. This would give us a better idea of the students’ performance. It would be ideal to use a data set also includes several years worth of data so that we can see if the trends shown persist from year to year. Finally, it would be interesting to incorporate other explanatory variables, particularly ones that policy makers could address through funding programs or laws. The results from this sort of study could be given to the state of Massachusetts so they can make more informed decisions about their schools.</p>
<p>Since our results strongly suggest that money is correlated to success on the SAT, it would be interesting to investigate the distribution of federal and state funding to public and charter schools in the state of Massachusetts.</p>
<p>We would also like to expand from just Massachusetts to other states across the country to get a broader view of the United States public education system. Massachusetts is a leader in education<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>. Many states are very different from Massachusetts and therefore could yield different results than what we found in this project.</p>
<hr>
</section>
</section>
<section id="citations-and-references" class="level1 unnumbered">
<h1 class="unnumbered">5. Citations and References</h1>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Strauss, Valerie. <em>What the numbers really tell us about America’s public schools</em>. Washington Post, March 2017. _https://www.washingtonpost.com/news/answer-sheet/wp/2017/03/06/what-the-numbers-really-tell-us-about-americas-public-schools/?noredirect=on&amp;utm_term=.d9a5b415678d<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Dalziel, Nigel. <em>Massachusetts Public Schools Data</em>. Kaggle, Aug.&nbsp;2017. Web. 19 Oct.&nbsp;2018. https://www.kaggle.com/ndalziel/massachusetts-public-schools-data<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Goldfarb, Zacchary. <em>These four charts show how the SAT favors rich, educated families</em>. Washington Post. March 2014. https://www.washingtonpost.com/news/wonk/wp/2014/03/05/these-four-charts-show-how-the-sat-favors-the-rich-educated-families/?noredirect=on&amp;utm_term=.aac2fb6c0f32<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Morad, Renee. <em>States With The Best Public School Systems</em> Forbes, Forbes Magazine, August 2018, https://www.forbes.com/sites/reneemorad/2018/07/31/states-with-the-best-public-school-systems/#649330883897<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Reis, Jacqueline. <em>Massachusetts Students Score among World Leaders on PISA Reading, Science and Math Tests</em>. Department of Education News, December 2016. http://www.doe.mass.edu/news/news.aspx?id=24050<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>